[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Packages.composer"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
